name: dart_algorand
description: >
               A dart library for interacting with the Algorand network.

               Algorand is an open source permissionless public blockchain based on
               a pure proof-of-stake consensus protocol.
version: 0.9.8
homepage: https://github.com/alvistar/dart_algorand

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  msgpack_dart: ^1.0.0
  base32: ^1.1.1
  pointycastle: ^3.0.1
  pinenacl: ^0.2.0
  collection: ^1.14.11
  dio: ^3.0.9
  built_value: ^7.0.9
  built_collection: ^4.3.2
  equatable: ^1.1.0
  http: ^0.12.0
  meta: ^1.1.8
  convert: ^2.1.1

dev_dependencies:
  build_runner: ^1.7.4
  built_value_generator: ^7.0.9
  pedantic: ^1.8.0
  test: ^1.6.0
